version: '3.8'

services:
  # C++ Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cpp_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8888:8888/udp"  # UDP game server port
    environment:
      - UDP_PORT=8888
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "8888:8888/udp"  # UDP proxy for game server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
